### ISSUE TITLE
SVXoroCalc

### ISSUE THREAD

**Issue by Stoned1337** [Manu098vm/SVResearches#3]
Can you Update your SVXoroCalc please? :)
For raid rewards and the other Stuff please

**Comment by Manu098vm** [comment]
Raid rewards are not one of my priorities. Expect something in the next few days for the other stuff (species, teratype, difficulty).

If you want to and you have the capabilities, other people have already figured out how species etc works though, so you could as well integrate my program with their researches.

**Comment by Stoned1337** [comment]
Unfortunately I have absolutely no idea about it.
Otherwise I would have gladly done it. but thanks anyway for the reply.

**Comment by joshuacode751** [comment]
![image](https://user-images.githubusercontent.com/32216817/205441669-10e19367-50ee-48d1-87e3-484a4bdf9e7e.png)
Im getting this error when changing the TID. How do I fix this?

**Comment by Manu098vm** [comment]
The program uses classic TID/SID, not Gen7+ TID/SID. You can check your classic TID/SID with PKHeX by hovering over your TID in any Pokémon.

**Comment by joshuacode751** [comment]
> The program uses classic TID/SID, not Gen7+ TID/SID. You can check your classic TID/SID with PKHeX by hovering over your TID in any Pokémon.

Ahh yeah I found it. The only problem I have now is that when I put my raid seed on the 2nd option the raid seed is completely changed and its not the previous raid.

**Comment by Manu098vm** [comment]
Yeah, as stated in the readme the program does not account for species/difficuly/teratype. Please wait patiently, I should release something about that in the next days.

**Comment by joshuacode751** [comment]
> Yeah, as stated in the readme the program does not account for species/difficuly/teratype. Please wait patiently, I should release something about that in the next days.

Oh I probably missed that. Thanks for heads up.

**Comment by Manu098vm** [comment]
The repository for the SVXoroCalc spiritual sequel has been pubblished: https://github.com/Manu098vm/Tera-Finder
Still need to implement item reward calculation, it's in the todo-list.

SVXoroCalc won't be updated in the future. I will probably archive this repo soon.
